### ISSUE TITLE
Allow loading a specific page by passing an url parameter

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/primerpedia#13]
Suggested [here](http://thread.gmane.org/gmane.science.linguistics.wikipedia.technical/65954/focus=65956) by oscar.vives

Question: using [query string](http://en.wikipedia.org/wiki/Query_string) (`location.search`) or [fragment identifier](http://en.wikipedia.org/wiki/Fragment_identifier) (`location.hash`)? A query string seems to be more appropriate from a semantic point of view (we'd be actually providing the app with parameters to dictate its output, rather than specifying a part of the complete output to be shown).

**Comment by joeinnes** [comment]
I'd like to have a crack at this

**Comment by waldyrious** [comment]
Fixed in #21 👍 thanks @joeinnes!
