### ISSUE TITLE
Update URL upon submitting a search query

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/primerpedia#22]
So that the URL can be shared. Background: #13.

**Comment by waldyrious** [comment]
#21 implemented performing searched from a parameter passed in the URL, so the format should be something like `https://waldyrious.github.io/primerpedia/?page=search%20terms` (I think the parameter could be renamed from `page=` to `search=`, for clarity).

Unfortunately, that functionality doesn't seem to be working at the moment. I wonder if this has anything to do with https://github.com/waldyrious/primerpedia/pull/26/commits/42cb953bb ? /cc @Jan-Ka, @joeinnes.

**Comment by Jan-Ka** [comment]
That is interesting. No, I don't think that is the culprit, it could be if it was a timing issue. Should be easy to fix - I will look into it if no one minds.

**Comment by waldyrious** [comment]
> the code currently checks for the `search` parameter instead of `page`. That's why your link (while http://waldyrious.net/primerpedia/?search=contractual%20terms does) does not work.

> Checking the History revealed 5920f6a9a69e586cec10883e5f78817cf3bd1c13 - appears that you changed that while documenting the source file.

Ah, how silly of me! Thanks for catching that :)

And yeah, #34 fixes this one as well as #7. You're on a roll! :fire:
