### ISSUE TITLE
Add permalink to current search query

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/primerpedia#23]
Having a link visible in the actual page would make sharing the page more evident than simply copying the URL, which would be available once #22 is implemented.

**Comment by Jan-Ka** [comment]
I think that this will be solved with the changes done for #22 , how about adding a Button to the bottom that uses `copy()` to copy the URL with Search Query for convenience?

**Comment by waldyrious** [comment]
I think the original description might have been slightly unclear. I edited the opening comment above to hopefully make it more explicit.

In any case, besides a simple link, having a "copy share URL" button would be even more convenient, of course. :+1:

**Comment by waldyrious** [comment]
This use case is now covered, with #42 merged.

(One *could* argue that having an actual link on the page would be helpful beyond the copy-to-clipboard feature, since users could copy its URL even if the JavaScript functionality fails to work, but the whole site would be useless without JavaScript anyway, so that's kind of irrelevant.)
