### ISSUE TITLE
Show a visible confirmation of link copied to clipboard

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/primerpedia#53]
When #42 is merged, we'll have a button to copy the URL of the page for sharing. But clicking the link has no visible effect in the page (at the time of writing). It would be nice to somehow inform the user that the link has indeed been copied.

A page-wide banner at the top of the page, popping up for a short while after pressing the button, would be ideal. Here's an [example from css-tricks](https://css-tricks.com/examples/PopFromTopMessage/).

**Comment by Jan-Ka** [comment]
I'll start this as soon as #42 is merged.

**Comment by Jan-Ka** [comment]
I'll start this as soon as #42 is merged.
